In [52]:
import pandas as pd
import numpy as np

In [46]:
train_df = pd.read_csv("/opt/ml/level2_klue_nlp-level2-nlp-11/dataset/train/train.csv")

In [47]:
train_df

,id,sentence,subject_entity,object_entity,label,source
0,0,〈Something〉는 조지 해리슨이 쓰고 비틀즈가 1969년 앨범 《Abbey R...,"{'word': '비틀즈', 'start_idx': 24, 'end_idx': 26...","{'word': '조지 해리슨', 'start_idx': 13, 'end_idx':...",no_relation,wikipedia
1,1,호남이 기반인 바른미래당·대안신당·민주평화당이 우여곡절 끝에 합당해 민생당(가칭)으...,"{'word': '민주평화당', 'start_idx': 19, 'end_idx': ...","{'word': '대안신당', 'start_idx': 14, 'end_idx': 1...",no_relation,wikitree
2,2,K리그2에서 성적 1위를 달리고 있는 광주FC는 지난 26일 한국프로축구연맹으로부터...,"{'word': '광주FC', 'start_idx': 21, 'end_idx': 2...","{'word': '한국프로축구연맹', 'start_idx': 34, 'end_idx...",org:member_of,wikitree
3,3,균일가 생활용품점 (주)아성다이소(대표 박정부)는 코로나19 바이러스로 어려움을 겪...,"{'word': '아성다이소', 'start_idx': 13, 'end_idx': ...","{'word': '박정부', 'start_idx': 22, 'end_idx': 24...",org:top_members/employees,wikitree
4,4,1967년 프로 야구 드래프트 1순위로 요미우리 자이언츠에게 입단하면서 등번호는 8...,"{'word': '요미우리 자이언츠', 'start_idx': 22, 'end_id...","{'word': '1967', 'start_idx': 0, 'end_idx': 3,...",no_relation,wikipedia
...,...,...,...,...,...,...
32465,32465,한국당은 7일 오전 9시부터 오후 5시까지 진행된 원내대표 및 정책위의장 후보자 등...,"{'word': '유기준', 'start_idx': 93, 'end_idx': 95...","{'word': '부산 서구·동구', 'start_idx': 100, 'end_id...",per:employee_of,wikitree
32466,32466,"법포는 다시 최시형, 서병학, 손병희 직계인 북접과 다시 서장옥, 전봉준, 김개남을...","{'word': '최시형', 'start_idx': 7, 'end_idx': 9, ...","{'word': '손병희', 'start_idx': 17, 'end_idx': 19...",per:colleagues,wikipedia
32467,32467,완도군(군수 신우철)이 국토교통부에서 실시한 '2019 교통문화지수 실태조사'에서 ...,"{'word': '완도군', 'start_idx': 0, 'end_idx': 2, ...","{'word': '신우철', 'start_idx': 7, 'end_idx': 9, ...",org:top_members/employees,wikitree
32468,32468,"중앙일보, JTBC 회장을 지낸 이후 중앙홀딩스 회장, 재단법인 한반도평화만들기 이...","{'word': 'JTBC', 'start_idx': 6, 'end_idx': 9,...","{'word': '중앙홀딩스', 'start_idx': 21, 'end_idx': ...",no_relation,wikipedia
32469,32469,화순군(군수 구충곤)은 17일 동면의 이장 20여 명이 코로나 19 예방을 위해 버...,"{'word': '화순군', 'start_idx': 0, 'end_idx': 2, ...","{'word': '구충곤', 'start_idx': 7, 'end_idx': 9, ...",org:top_members/employees,wikitree

In [64]:
per_other_family_df = pd.read_csv("./per:other_family.csv")
per_place_of_death = pd.read_csv("./per:place_of_death.csv")
per_place_of_residence = pd.read_csv("./per:place_of_residence.csv")
per_place_of_birth = pd.read_csv("./per:place_of_birth.csv")

concatenate_list = [per_other_family_df, per_place_of_death , per_place_of_residence , per_place_of_birth ]
print(f"per_other_family_df 의 개수 : {len(per_other_family_df)}")
print(f"per_place_of_death 의 개수 : {len(per_place_of_death)}")
print(f"per_place_of_residence 의 개수 : {len(per_place_of_residence)}")
print(f"per_place_of_birth 의 개수 : {len(per_place_of_birth)}")

per_other_family_df 의 개수 : 167
per_place_of_death 의 개수 : 27
per_place_of_residence 의 개수 : 46
per_place_of_birth 의 개수 : 91

In [66]:
concat_df = pd.concat(concatenate_list, join="outer" )
concat_df

,id,sentence,label,source,subject_entity,object_entity
0,712,광남 김익훈은 1619년 김장생의 손자이자 참판을 지내고 증 의정부영의정에 추증된 ...,per:other_family,wikipedia,"{'word': '김장생', 'start_idx': 14, 'end_ids': 17...","{'word': '김반', 'start_idx': 46, 'end_ids': 48,..."
1,1537,"충숙왕의 제5비인 수비 권씨는 그녀의 외사촌이며, 훗날 반란을 일으킨 조일신은 홍씨...",per:other_family,wikipedia,"{'word': '홍', 'start_idx': 44, 'end_ids': 45, ...","{'word': '조일신', 'start_idx': 39, 'end_ids': 42..."
2,3852,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...",per:other_family,wikipedia,"{'word': '성삼문', 'start_idx': 6, 'end_ids': 9, ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,..."
3,3856,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...",per:other_family,wikipedia,"{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼고', 'start_idx': 16, 'end_ids': 19..."
4,3857,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...",per:other_family,wikipedia,"{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼빙', 'start_idx': 11, 'end_ids': 14..."
...,...,...,...,...,...,...
86,8416,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.",per:place_of_birth,wikipedia,"{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '보클뤼즈주', 'start_idx': 22, 'end_ids': ..."
87,8417,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.",per:place_of_birth,wikipedia,"{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '카르팡트라', 'start_idx': 28, 'end_ids': ..."
88,8434,이광재는 강원도 평창군에서 태어나 평창초등학교를 다니다가 정선군 신동읍의 예미초등학...,per:place_of_birth,wikipedia,"{'word': '이광재', 'start_idx': 0, 'end_ids': 3, ...","{'word': '평창군', 'start_idx': 9, 'end_ids': 12,..."
89,8442,"구자철 (具滋哲, 1989년 2월 27일, 대한민국 충청남도 논산시 ~)은 대한민국...",per:place_of_birth,wikipedia,"{'word': '구자철', 'start_idx': 0, 'end_ids': 3, ...","{'word': '충청남도', 'start_idx': 29, 'end_ids': 3..."
90,8579,로빈 리한나 펜티는 은퇴한 회계사 모니카 브레드웨이트와 의류 공장 창고 책임자를 맡...,per:place_of_birth,wikipedia,"{'word': '로빈 리한나 펜티', 'start_idx': 0, 'end_ids...","{'word': '세인트마이클구', 'start_idx': 84, 'end_ids'..."

In [68]:
print(f"concatenate_df 의 개수 : {len(concat_df)}")

concatenate_df 의 개수 : 331

In [69]:
subjt = concat_df['subject_entity'].apply(lambda x: pd.Series(eval(x))).add_prefix('subj_')
objt = concat_df['object_entity'].apply(lambda x: pd.Series(eval(x))).add_prefix('obj_')
concat_df = pd.concat([concat_df[["sentence", "subject_entity", "object_entity", "label", "source"]], subjt, objt], axis=1)

In [70]:
concat_df

,sentence,subject_entity,object_entity,label,source,subj_word,subj_start_idx,subj_end_ids,subj_type,obj_word,obj_start_idx,obj_end_ids,obj_type
0,광남 김익훈은 1619년 김장생의 손자이자 참판을 지내고 증 의정부영의정에 추증된 ...,"{'word': '김장생', 'start_idx': 14, 'end_ids': 17...","{'word': '김반', 'start_idx': 46, 'end_ids': 48,...",per:other_family,wikipedia,김장생,14,17,PER,김반,46,48,PER
1,"충숙왕의 제5비인 수비 권씨는 그녀의 외사촌이며, 훗날 반란을 일으킨 조일신은 홍씨...","{'word': '홍', 'start_idx': 44, 'end_ids': 45, ...","{'word': '조일신', 'start_idx': 39, 'end_ids': 42...",per:other_family,wikipedia,홍,44,45,PER,조일신,39,42,PER
2,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성삼문', 'start_idx': 6, 'end_ids': 9, ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...",per:other_family,wikipedia,성삼문,6,9,PER,성희,71,73,PER
3,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼고', 'start_idx': 16, 'end_ids': 19...",per:other_family,wikipedia,성희,71,73,PER,성삼고,16,19,PER
4,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼빙', 'start_idx': 11, 'end_ids': 14...",per:other_family,wikipedia,성희,71,73,PER,성삼빙,11,14,PER
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '보클뤼즈주', 'start_idx': 22, 'end_ids': ...",per:place_of_birth,wikipedia,에두아르 달라디에,0,9,PER,보클뤼즈주,22,27,LOC
87,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '카르팡트라', 'start_idx': 28, 'end_ids': ...",per:place_of_birth,wikipedia,에두아르 달라디에,0,9,PER,카르팡트라,28,33,LOC
88,이광재는 강원도 평창군에서 태어나 평창초등학교를 다니다가 정선군 신동읍의 예미초등학...,"{'word': '이광재', 'start_idx': 0, 'end_ids': 3, ...","{'word': '평창군', 'start_idx': 9, 'end_ids': 12,...",per:place_of_birth,wikipedia,이광재,0,3,PER,평창군,9,12,LOC
89,"구자철 (具滋哲, 1989년 2월 27일, 대한민국 충청남도 논산시 ~)은 대한민국...","{'word': '구자철', 'start_idx': 0, 'end_ids': 3, ...","{'word': '충청남도', 'start_idx': 29, 'end_ids': 3...",per:place_of_birth,wikipedia,구자철,0,3,PER,충청남도,29,33,LOC
90,로빈 리한나 펜티는 은퇴한 회계사 모니카 브레드웨이트와 의류 공장 창고 책임자를 맡...,"{'word': '로빈 리한나 펜티', 'start_idx': 0, 'end_ids...","{'word': '세인트마이클구', 'start_idx': 84, 'end_ids'...",per:place_of_birth,wikipedia,로빈 리한나 펜티,0,9,PER,세인트마이클구,84,91,LOC

In [71]:
from functools import partial

def change_alpha(x, col1 , col2):
    sub_word, obj_word = x[col1] , x[col2]

    if (sub_word.isalpha() | obj_word.isalpha()) :
        return False
    else :
        return True


ff = partial(change_alpha , col1 = "subj_word", col2="obj_word")

In [72]:
concat_df[['is_alpha']]= concat_df.apply(lambda x : ff(x),axis=1)
concat_df['is_alpha'].value_counts()

False    302
True      29
Name: is_alpha, dtype: int64

In [73]:
remove_eng_word = (concat_df.is_alpha == False)
remove_eng_concat_df = concat_df.loc[remove_eng_word, :]

In [74]:
remove_eng_concat_df

,sentence,subject_entity,object_entity,label,source,subj_word,subj_start_idx,subj_end_ids,subj_type,obj_word,obj_start_idx,obj_end_ids,obj_type,is_alpha
0,광남 김익훈은 1619년 김장생의 손자이자 참판을 지내고 증 의정부영의정에 추증된 ...,"{'word': '김장생', 'start_idx': 14, 'end_ids': 17...","{'word': '김반', 'start_idx': 46, 'end_ids': 48,...",per:other_family,wikipedia,김장생,14,17,PER,김반,46,48,PER,False
1,"충숙왕의 제5비인 수비 권씨는 그녀의 외사촌이며, 훗날 반란을 일으킨 조일신은 홍씨...","{'word': '홍', 'start_idx': 44, 'end_ids': 45, ...","{'word': '조일신', 'start_idx': 39, 'end_ids': 42...",per:other_family,wikipedia,홍,44,45,PER,조일신,39,42,PER,False
2,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성삼문', 'start_idx': 6, 'end_ids': 9, ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...",per:other_family,wikipedia,성삼문,6,9,PER,성희,71,73,PER,False
3,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼고', 'start_idx': 16, 'end_ids': 19...",per:other_family,wikipedia,성희,71,73,PER,성삼고,16,19,PER,False
4,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼빙', 'start_idx': 11, 'end_ids': 14...",per:other_family,wikipedia,성희,71,73,PER,성삼빙,11,14,PER,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '보클뤼즈주', 'start_idx': 22, 'end_ids': ...",per:place_of_birth,wikipedia,에두아르 달라디에,0,9,PER,보클뤼즈주,22,27,LOC,False
87,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '카르팡트라', 'start_idx': 28, 'end_ids': ...",per:place_of_birth,wikipedia,에두아르 달라디에,0,9,PER,카르팡트라,28,33,LOC,False
88,이광재는 강원도 평창군에서 태어나 평창초등학교를 다니다가 정선군 신동읍의 예미초등학...,"{'word': '이광재', 'start_idx': 0, 'end_ids': 3, ...","{'word': '평창군', 'start_idx': 9, 'end_ids': 12,...",per:place_of_birth,wikipedia,이광재,0,3,PER,평창군,9,12,LOC,False
89,"구자철 (具滋哲, 1989년 2월 27일, 대한민국 충청남도 논산시 ~)은 대한민국...","{'word': '구자철', 'start_idx': 0, 'end_ids': 3, ...","{'word': '충청남도', 'start_idx': 29, 'end_ids': 3...",per:place_of_birth,wikipedia,구자철,0,3,PER,충청남도,29,33,LOC,False
90,로빈 리한나 펜티는 은퇴한 회계사 모니카 브레드웨이트와 의류 공장 창고 책임자를 맡...,"{'word': '로빈 리한나 펜티', 'start_idx': 0, 'end_ids...","{'word': '세인트마이클구', 'start_idx': 84, 'end_ids'...",per:place_of_birth,wikipedia,로빈 리한나 펜티,0,9,PER,세인트마이클구,84,91,LOC,False

In [75]:
remove_eng_concat_df = remove_eng_concat_df.drop(
    ["subj_start_idx", "subj_end_ids", "subj_type", "obj_start_idx", "obj_end_ids", "obj_type", "subj_word", "obj_word", "is_alpha"], axis=1)

In [76]:
remove_eng_concat_df

,sentence,subject_entity,object_entity,label,source
0,광남 김익훈은 1619년 김장생의 손자이자 참판을 지내고 증 의정부영의정에 추증된 ...,"{'word': '김장생', 'start_idx': 14, 'end_ids': 17...","{'word': '김반', 'start_idx': 46, 'end_ids': 48,...",per:other_family,wikipedia
1,"충숙왕의 제5비인 수비 권씨는 그녀의 외사촌이며, 훗날 반란을 일으킨 조일신은 홍씨...","{'word': '홍', 'start_idx': 44, 'end_ids': 45, ...","{'word': '조일신', 'start_idx': 39, 'end_ids': 42...",per:other_family,wikipedia
2,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성삼문', 'start_idx': 6, 'end_ids': 9, ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...",per:other_family,wikipedia
3,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼고', 'start_idx': 16, 'end_ids': 19...",per:other_family,wikipedia
4,"그의 아들 성삼문, 성삼빙, 성삼고, 성삼성과 손자 네 명이 모두 처형당하여 그의 ...","{'word': '성희', 'start_idx': 71, 'end_ids': 73,...","{'word': '성삼빙', 'start_idx': 11, 'end_ids': 14...",per:other_family,wikipedia
...,...,...,...,...,...
86,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '보클뤼즈주', 'start_idx': 22, 'end_ids': ...",per:place_of_birth,wikipedia
87,"에두아르 달라디에는 1884년, 프랑스 보클뤼즈주 카르팡트라 에서 태어났다.","{'word': '에두아르 달라디에', 'start_idx': 0, 'end_ids...","{'word': '카르팡트라', 'start_idx': 28, 'end_ids': ...",per:place_of_birth,wikipedia
88,이광재는 강원도 평창군에서 태어나 평창초등학교를 다니다가 정선군 신동읍의 예미초등학...,"{'word': '이광재', 'start_idx': 0, 'end_ids': 3, ...","{'word': '평창군', 'start_idx': 9, 'end_ids': 12,...",per:place_of_birth,wikipedia
89,"구자철 (具滋哲, 1989년 2월 27일, 대한민국 충청남도 논산시 ~)은 대한민국...","{'word': '구자철', 'start_idx': 0, 'end_ids': 3, ...","{'word': '충청남도', 'start_idx': 29, 'end_ids': 3...",per:place_of_birth,wikipedia
90,로빈 리한나 펜티는 은퇴한 회계사 모니카 브레드웨이트와 의류 공장 창고 책임자를 맡...,"{'word': '로빈 리한나 펜티', 'start_idx': 0, 'end_ids...","{'word': '세인트마이클구', 'start_idx': 84, 'end_ids'...",per:place_of_birth,wikipedia

In [77]:
pororo_ner_df = pd.concat([train_df, remove_eng_concat_df], join="outer")

In [78]:
#reset id , id type
pororo_ner_df['id'] = np.arange(len(pororo_ner_df))
pororo_ner_df = pororo_ner_df.astype({'id':'int64'})

In [80]:
#추출전 데이터 shuffle
pororo_ner_df = pororo_ner_df.sample(frac=1)
pororo_ner_df

,id,sentence,subject_entity,object_entity,label,source
28320,28320,"유성호 교수는 ""아 고려대""라고 묻자 장도연 씨는 ""아뇨 고대 아니고 경희대...""...","{'word': '유성호', 'start_idx': 0, 'end_idx': 2, ...","{'word': '고려대', 'start_idx': 11, 'end_idx': 13...",no_relation,wikitree
7589,7589,"가디언은 이와 함께 헝가리 소설가 크러스너호르커이 라슬로, 폴란드 작가 올가 토카주...","{'word': '크러스너호르커이 라슬로', 'start_idx': 19, 'end...","{'word': '소설가', 'start_idx': 15, 'end_idx': 17...",per:title,wikitree
26583,26583,"그러나 2007년, 소속사의 재정 상황 악화로 인해 오소녀의 데뷔가 완전히 엎어졌고...","{'word': '원더걸스', 'start_idx': 73, 'end_idx': 7...","{'word': 'JYP 엔터테인먼트', 'start_idx': 57, 'end_i...",per:employee_of,wikipedia
24823,24823,"루안 에메라(Louane Emera, 1996년 11월 26일 ~)는 프랑스의 가수...","{'word': '루안 에메라', 'start_idx': 0, 'end_idx': ...","{'word': '가수, 배우', 'start_idx': 44, 'end_idx':...",per:title,wikipedia
25235,25235,방민진 유진투자증권 연구원은 “HDC현대산업개발 컨소시엄의 인수가 예상대로 마무리될...,"{'word': '아시아나항공', 'start_idx': 91, 'end_idx':...","{'word': 'HDC현대산업개발', 'start_idx': 17, 'end_id...",no_relation,wikitree
...,...,...,...,...,...,...
15489,15489,"전국시도교육감협의회는(회장 김승환, 이하 ‘협의회’) 13일 국회를 통과한 “유치원...","{'word': '전국시도교육감협의회', 'start_idx': 0, 'end_id...","{'word': '김승환', 'start_idx': 15, 'end_idx': 17...",org:top_members/employees,wikitree
5433,5433,이어 1940년 그리스 국립 리사이틀 테아트레(Lyric Theatre)에서 주페의...,"{'word': '아테네', 'start_idx': 107, 'end_idx': 1...","{'word': '그리스', 'start_idx': 9, 'end_idx': 11,...",no_relation,wikipedia
15770,15770,주례를 맡은 가수 태진아(조방헌·66) 씨도 함께 등장했다.,"{'word': '태진아', 'start_idx': 10, 'end_idx': 12...","{'word': '조방헌', 'start_idx': 14, 'end_idx': 16...",per:alternate_names,wikitree
16374,16374,(재키 로빈슨이 콤프턴의 팀 동료였다) 또한 콤프턴은 로즈볼(미국 대학간의 미식 축...,"{'word': '재키 로빈슨', 'start_idx': 1, 'end_idx': ...","{'word': 'UCLA', 'start_idx': 54, 'end_idx': 5...",no_relation,wikipedia
27543,27543,"김장원 IBK투자증권 연구원은 “조현아 전 부사장과 KCGI, 반도건설이 지분을 공...","{'word': '조원태', 'start_idx': 63, 'end_idx': 65...","{'word': '이명희', 'start_idx': 86, 'end_idx': 88...",no_relation,wikitree

In [81]:
pororo_ner_df.to_csv('./pororo_ner_df.csv',index=False, encoding = 'utf-8')